FROM python:3.9-slim-buster

RUN apt-get update 
RUN apt-get install -y openjdk-11-jdk-headless
RUN pip install pyspark==3.2.3 

COPY spark/* /app/

RUN pip install -r /app/requirements.txt

WORKDIR /app

CMD ["spark-submit", "--master", "local[*]", "streaming.py"]