FROM python:3.9-slim-buster

ENV FLASK_APP=app.py
ENV FLASK_DEBUG=True

COPY flask/ /app/
RUN pip install -r /app/requirements.txt

WORKDIR /app
#EXPOSE 5029
#CMD ["flask", "run", "--host=0.0.0.0"]
CMD ["python", "app.py"]

